### ISSUE TITLE
Add a "base path" option for Maker commands.

### ISSUE THREAD

**Issue by b00giZm** [geekcell/ddd-symfony-bundle#40]
By default, when generating classes with the included Maker commands, we're storing then under `src`. It would be great to add an option to set something like a "base path", such as

```bash
bin/console make:ddd:model --aggregate-root --basePath=src/Foo
```

which then would generate a model and related classes below `src/Foo/Model`.

**Comment by janvt** [comment]
Resolved by https://github.com/geekcell/ddd-symfony-bundle/pull/41
